USE AdventureWorks2019
BEGIN
	DECLARE @var1 INT = 5

	IF @var1 > 5
		PRINT('YES')
	ELSE
		PRINT('NO')
		PRINT(CAST(@var1 AS NVARCHAR) + ' IS SMALLER/EQUAL 5')
END

-- USE @@ROWCOUNT
BEGIN
	DECLARE @ID INT
	SET @ID = 20

	SELECT * FROM [Person].[Person]
	WHERE [BusinessEntityID]=@ID

	IF @@ROWCOUNT > 0
		PRINT('THERE IS A PERSON WITH ID = ' + CAST(@ID AS NVARCHAR))
	ELSE
		PRINT('THERE IS NO ANY PERSON WITH ID = ' + CAST(@ID AS NVARCHAR))
END